### ISSUE TITLE
Question on Bucket Configuration

### ISSUE THREAD

**Issue by oliverturner** [dittto/serverless-s3-assets#1]
Hoping you can shed some light on how I can make my `s3assets` bucket website-enabled.

The following rules create a bucket with the desired properties: 

```yml
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
```

...but they also conflict with the bucket created by `s3Assets`. How would I apply them to that config?

Many thanks in advance
